#We use this worflow to install Python dependencies.

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    barncehs: ["main"]

permission:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -a pip install -upgrade pip
        pip install -r requirements.txt
